modLoader="javafml"
loaderVersion="[41,)"
license="GNU General Public License v3.0"
issueTrackerURL="https://github.com/ApexStudios-Dev/FantasyDice/issues"

[[mods]]
	modId="fantasydice"
	version="${file.jarVersion}"
	displayName="Fantasy's Dice"
	updateJSONURL="https://raw.githubusercontent.com/ApexStudios-Dev/Version/master/fantasydice.json"
	displayURL="https://www.curseforge.com/minecraft/mc-mods/fantasys-dice"
	logoFile="banner.png"
	credits="Apex - Programming, FantasyGaming - Texture Artist"
	authors="Apex, FantasyGaming"
	description="Mod requested by FantasyGaming which adds 6 & 20 Sided Dice to the game of varying types."

[[dependencies.fantasydice]]
	modId="forge"
	mandatory=true
	versionRange="[41.0.88,)"
	ordering="AFTER"
	side="BOTH"
[[dependencies.fantasydice]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.19,1.20)"
	ordering="AFTER"
	side="BOTH"
[[dependencies.fantasydice]]
	modId="commonality"
	mandatory=true
	versionRange="[2.0.0,3.0.0)"
	ordering="AFTER"
	side="BOTH"
[[dependencies.fantasydice]]
	modId="apexcore"
	mandatory=true
	versionRange="[5.0.0,6.0.0)"
	ordering="AFTER"
	side="BOTH"
[[dependencies.fantasydice]]
	modId="jei"
	mandatory=false
	versionRange="[11.0.+,)"
	ordering="AFTER"
	side="BOTH"