name: Run Project Tests

on:
  pull_request:
    branches:
      - '**'
    tags-ignore:
      - 'v**'
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v**'

jobs:
  # Run tests to ensure mod runs fine
  tests:
    uses: ApexStudios-Dev/.github/.github/workflows/call_tests.yml@master
    with:
      notification_color: 0xE27E8B
    secrets:
      DISCORD_CI_WEBHOOK: ${{ secrets.DISCORD_CI_WEBHOOK }}